//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class changeEntities : DbContext
    {
        public changeEntities()
            : base("name=changeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckJsonData_r> CheckJsonData_r { get; set; }
        public virtual DbSet<downloadDocumentsAttachedByCheck_r> downloadDocumentsAttachedByCheck_r { get; set; }
        public virtual DbSet<downloadDocumentsAttachedByCheck_s> downloadDocumentsAttachedByCheck_s { get; set; }
        public virtual DbSet<downloadPDF_r> downloadPDF_r { get; set; }
        public virtual DbSet<downloadPDF_s> downloadPDF_s { get; set; }
        public virtual DbSet<getDocumentsAttachedReplyInfo_r> getDocumentsAttachedReplyInfo_r { get; set; }
        public virtual DbSet<getDocumentsAttachedReplyInfo_s> getDocumentsAttachedReplyInfo_s { get; set; }
        public virtual DbSet<getEdiNo_r> getEdiNo_r { get; set; }
        public virtual DbSet<getEdiNo_s> getEdiNo_s { get; set; }
        public virtual DbSet<Httppost_s> Httppost_s { get; set; }
        public virtual DbSet<queryFormResult_s> queryFormResult_s { get; set; }
        public virtual DbSet<sendAgent_s> sendAgent_s { get; set; }
        public virtual DbSet<sendCusFile_r> sendCusFile_r { get; set; }
        public virtual DbSet<sendCusFile_r1> sendCusFile_r1 { get; set; }
        public virtual DbSet<sendCusFile_r2> sendCusFile_r2 { get; set; }
        public virtual DbSet<sendCusFile_r3> sendCusFile_r3 { get; set; }
        public virtual DbSet<uploadDocumentsAttached_r> uploadDocumentsAttached_r { get; set; }
        public virtual DbSet<uploadDocumentsAttached_s> uploadDocumentsAttached_s { get; set; }
        public virtual DbSet<uploadFileForSW_r> uploadFileForSW_r { get; set; }
        public virtual DbSet<uploadFileForSW_s> uploadFileForSW_s { get; set; }
        public virtual DbSet<报关单表体> 报关单表体 { get; set; }
        public virtual DbSet<报关单表头> 报关单表头 { get; set; }
        public virtual DbSet<报关单回执信息> 报关单回执信息 { get; set; }
        public virtual DbSet<报关单集装箱> 报关单集装箱 { get; set; }
        public virtual DbSet<报关单随附单据> 报关单随附单据 { get; set; }
        public virtual DbSet<报税单表体> 报税单表体 { get; set; }
        public virtual DbSet<报税单表头> 报税单表头 { get; set; }
        public virtual DbSet<标记号码附件> 标记号码附件 { get; set; }
        public virtual DbSet<代理委托> 代理委托 { get; set; }
        public virtual DbSet<代理委托回执信息> 代理委托回执信息 { get; set; }
        public virtual DbSet<归类补充申报> 归类补充申报 { get; set; }
        public virtual DbSet<价格补充申报> 价格补充申报 { get; set; }
        public virtual DbSet<其他包装信息> 其他包装信息 { get; set; }
        public virtual DbSet<企业承诺信息> 企业承诺信息 { get; set; }
        public virtual DbSet<企业资质> 企业资质 { get; set; }
        public virtual DbSet<请求头> 请求头 { get; set; }
        public virtual DbSet<申请单证信息> 申请单证信息 { get; set; }
        public virtual DbSet<使用人信息> 使用人信息 { get; set; }
        public virtual DbSet<税费计算结果> 税费计算结果 { get; set; }
        public virtual DbSet<特许权使用费申请> 特许权使用费申请 { get; set; }
        public virtual DbSet<许可证VIN信息> 许可证VIN信息 { get; set; }
        public virtual DbSet<许可证信息> 许可证信息 { get; set; }
        public virtual DbSet<原产地补充申报> 原产地补充申报 { get; set; }
        public virtual DbSet<原产地证明项号关联关系> 原产地证明项号关联关系 { get; set; }
        public virtual DbSet<queryFormResult_r> queryFormResult_r { get; set; }
        public virtual DbSet<sendAgent_r> sendAgent_r { get; set; }
        public virtual DbSet<报关单随附单证> 报关单随附单证 { get; set; }
        public virtual DbSet<nc_getEdiNo> nc_getEdiNo { get; set; }
    }
}
