//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTA_INF_REC
    {
        public string cond_id { get; set; }
        public string t_flag { get; set; }
        public short item_id { get; set; }
        public string b_cut { get; set; }
        public string e_cut { get; set; }
        public string bull_flag { get; set; }
        public string contents_0 { get; set; }
        public string contents_1 { get; set; }
    }
}
