//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTA_NAM_REC
    {
        public short item_code { get; set; }
        public string item_name { get; set; }
        public string item_flag { get; set; }
        public string item_type { get; set; }
    }
}
