//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVYTYPE
    {
        public string CUT_MODE { get; set; }
        public string ABBR_CUT { get; set; }
        public string FULL_CUT { get; set; }
    }
}
