//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public int ObjectID { get; set; }
        public string entablename { get; set; }
        public string chtablename { get; set; }
        public string encolmnname { get; set; }
        public string chcolmnname { get; set; }
    }
}
