//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class nc_getEdiNo
    {
        public int id { get; set; }
        public string TextBox1 { get; set; }
        public string txtAdress { get; set; }
        public string txtData { get; set; }
        public string txtPassword { get; set; }
        public string txtPrivateKey { get; set; }
        public string txtPublicKey { get; set; }
        public string txtSender { get; set; }
        public string txtRecever { get; set; }
        public string txtMiWen { get; set; }
        public string txtMingWen { get; set; }
    }
}
