//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class sendCusFile_r2
    {
        public int id { get; set; }
        public string T_SWGD_FORM_LIST { get; set; }
        public string T_SWGD_FORM_CLASSIFYSUP { get; set; }
        public string T_SWGD_FORM_ORIGINALSUP { get; set; }
        public string T_SWGD_FORM_PRICESUP { get; set; }
        public string LIMIT_VIN_PAIR { get; set; }
    }
}
