//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class sendCusFile_r1
    {
        public int id { get; set; }
        public string T_SWGD_FORM_HEAD { get; set; }
        public string LIST_LIMIT_SUP_LIST { get; set; }
        public string T_SWGD_FORM_CONTAINER { get; set; }
        public string T_SWGD_FORM_CERTIFICATE { get; set; }
        public string T_SWGD_FORM_EDOC { get; set; }
        public string T_SWGD_FORM_ECO { get; set; }
        public string T_DEC_MARK_LOB { get; set; }
        public string T_DEC_REQUEST_CERT { get; set; }
        public string T_DEC_OTHER_PACK { get; set; }
        public string T_DEC_COP_LIMIT { get; set; }
        public string T_DEC_COP_PROMISE { get; set; }
        public string T_DEC_USER { get; set; }
        public string T_SWGD_SDDTAX_HEAD { get; set; }
        public string T_SWGD_SDDTAX_LIST { get; set; }
        public string T_SWGD_SDDTAX_DETAILS { get; set; }
        public string T_DEC_ROYALTY_FEE { get; set; }
    }
}
