//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadFileForSW_s
    {
        public int id { get; set; }
        public string ediNo { get; set; }
        public string edoccode { get; set; }
        public string tradeFileName { get; set; }
        public string fileDigest { get; set; }
        public string declCode { get; set; }
        public string declName { get; set; }
        public string signunit { get; set; }
        public byte[] datas { get; set; }
    }
}
