//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadDocumentsAttached_s
    {
        public int id { get; set; }
        public string preEntryId { get; set; }
        public string fileName { get; set; }
        public string declName { get; set; }
        public string signCert { get; set; }
        public string formatType { get; set; }
        public string signUnit { get; set; }
        public string operFlag { get; set; }
        public string edocOwnerCode { get; set; }
        public string opNote { get; set; }
        public string customsCode { get; set; }
        public string edocOwnerName { get; set; }
        public string fileType { get; set; }
        public string loginName { get; set; }
        public string declType { get; set; }
        public string declCode { get; set; }
        public string declTime { get; set; }
        public string entryId { get; set; }
        public string tradeCode { get; set; }
        public string dataSource { get; set; }
        public string ieFlag { get; set; }
    }
}
