//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldFirstDistrict
    {
        public string CCM_UUID { get; set; }
        public string INDEXID { get; set; }
        public string ITEMCODE { get; set; }
        public string ISO2 { get; set; }
        public string ISO3 { get; set; }
        public string ITEMNAME { get; set; }
        public string ENAME { get; set; }
        public string STATE { get; set; }
        public string CIQ { get; set; }
        public string OLDCODE { get; set; }
        public string OLDCNAME { get; set; }
        public string PARENTCODE { get; set; }
        public string FLAG { get; set; }
        public Nullable<System.DateTime> LASTUPDATE { get; set; }
        public string LEAFFLAG { get; set; }
        public string VERSION { get; set; }
        public string FMK_ARCHIVE_FLAG { get; set; }
        public string OTHER_FLAG { get; set; }
    }
}
