//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 代理委托回执信息
    {
        public int id { get; set; }
        public string ediNo { get; set; }
        public string conSignNo { get; set; }
        public string responseCode { get; set; }
        public string responseNotes { get; set; }
        public string dataResult { get; set; }
    }
}
