//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 代理委托
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string ediNo { get; set; }
        public string userName { get; set; }
        public string copCusCode { get; set; }
        public string gname { get; set; }
        public string codeTS { get; set; }
        public string declTotal { get; set; }
        public string iEDate { get; set; }
        public string listNo { get; set; }
        public string tradeMode { get; set; }
        public string curr { get; set; }
        public string oriCountry { get; set; }
        public string otherNote { get; set; }
        public string consignIcCode { get; set; }
        public string consignIcName { get; set; }
        public string consignPhone { get; set; }
        public Nullable<decimal> consignDate { get; set; }
        public string entryId { get; set; }
        public string cusCode { get; set; }
        public string decEntryId { get; set; }
        public string receiveDate { get; set; }
        public string edocCode { get; set; }
        public string otherRecInfo { get; set; }
        public string declarePrice { get; set; }
        public string promiseNote { get; set; }
        public string declIcCode { get; set; }
        public string declIcName { get; set; }
        public string declTele { get; set; }
        public string note { get; set; }
        public string payerCode { get; set; }
        public string tradeCode { get; set; }
        public string agentCode { get; set; }
    }
}
