//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 价格补充申报
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string brandCn { get; set; }
        public string brandEn { get; set; }
        public string buyer { get; set; }
        public string buyerContact { get; set; }
        public string buyerAddr { get; set; }
        public string buyerTel { get; set; }
        public string seller { get; set; }
        public string sellerContact { get; set; }
        public string sellerAddr { get; set; }
        public string sellerTel { get; set; }
        public string factory { get; set; }
        public string factoryContact { get; set; }
        public string factoryAddr { get; set; }
        public string factoryTel { get; set; }
        public string contrNo { get; set; }
        public string contrDate { get; set; }
        public string invoiceNo { get; set; }
        public string invoiceDate { get; set; }
        public string iBabRel { get; set; }
        public string iPriceEffect { get; set; }
        public string iPriceClose { get; set; }
        public string iOtherLimited { get; set; }
        public string iOtherEffect { get; set; }
        public string iNote1 { get; set; }
        public string iIsUsefee { get; set; }
        public string iIsProfit { get; set; }
        public string iNote2 { get; set; }
        public string curr { get; set; }
        public string invoicePrice { get; set; }
        public string invoiceAmount { get; set; }
        public string invoiceNote { get; set; }
        public string goodsPrice { get; set; }
        public string goodsAmount { get; set; }
        public string goodsNote { get; set; }
        public string iCommissionPrice { get; set; }
        public string iCommissionAmount { get; set; }
        public string iCommissionNote { get; set; }
        public string iContainerPrice { get; set; }
        public string iContainerAmount { get; set; }
        public string iContainerNote { get; set; }
        public string iPackPrice { get; set; }
        public string iPackAmount { get; set; }
        public string iPackNote { get; set; }
        public string iPartPrice { get; set; }
        public string iPartAmount { get; set; }
        public string iPartNote { get; set; }
        public string iToolPrice { get; set; }
        public string iToolAmount { get; set; }
        public string iToolNote { get; set; }
        public string iLossPrice { get; set; }
        public string iLossAmount { get; set; }
        public string iLossNote { get; set; }
        public string iDesignPrice { get; set; }
        public string iDesignAmount { get; set; }
        public string iDesignNote { get; set; }
        public string iUsefeePrice { get; set; }
        public string iUsefeeAmount { get; set; }
        public string iUsefeeNote { get; set; }
        public string iProfitPrice { get; set; }
        public string iProfitAmount { get; set; }
        public string iProfitNote { get; set; }
        public string iFeePrice { get; set; }
        public string iFeeAmount { get; set; }
        public string iFeeNote { get; set; }
        public string iOtherPrice { get; set; }
        public string iOtherAmount { get; set; }
        public string iOtherNote { get; set; }
        public string iInsurPrice { get; set; }
        public string iInsurAmount { get; set; }
        public string iInsurNote { get; set; }
        public string eIsDutyDel { get; set; }
        public string isSecret { get; set; }
        public string agentCode { get; set; }
        public string agentName { get; set; }
        public string agentType { get; set; }
        public string declAddr { get; set; }
        public string declPost { get; set; }
        public string declTel { get; set; }
        public string declNo { get; set; }
        public string declName { get; set; }
    }
}
