//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 其他包装信息
    {
        public int id { get; set; }
        public int oid { get; set; }
        public decimal packQty { get; set; }
        public string packType { get; set; }
    }
}
