//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 原产地证明项号关联关系
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string certType { get; set; }
        public string ecoCertNo { get; set; }
        public string decGNo { get; set; }
        public string ecoGNo { get; set; }
        public string extendFiled { get; set; }
    }
}
