//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 归类补充申报
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string brandCn { get; set; }
        public string brandEn { get; set; }
        public string buyer { get; set; }
        public string buyerContact { get; set; }
        public string buyerAddr { get; set; }
        public string buyerTel { get; set; }
        public string seller { get; set; }
        public string sellerContact { get; set; }
        public string sellerAddr { get; set; }
        public string sellerTel { get; set; }
        public string factory { get; set; }
        public string factoryContact { get; set; }
        public string factoryAddr { get; set; }
        public string factoryTel { get; set; }
        public string contrNo { get; set; }
        public string contrDate { get; set; }
        public string invoiceNo { get; set; }
        public string invoiceDate { get; set; }
        public string gNameOther { get; set; }
        public string codeTsOther { get; set; }
        public string isClassDecision { get; set; }
        public string decisionNo { get; set; }
        public string codeTsDecision { get; set; }
        public string decisionCus { get; set; }
        public string isSampleTest { get; set; }
        public string gOptions { get; set; }
        public string gOptionsNote { get; set; }
        public string otherNote { get; set; }
        public string isSecret { get; set; }
        public string agentCode { get; set; }
        public string agentName { get; set; }
        public string agentType { get; set; }
        public string declAddr { get; set; }
        public string declPost { get; set; }
        public string declTel { get; set; }
        public string declNo { get; set; }
        public string declName { get; set; }
    }
}
