//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报关单集装箱
    {
        public int id { get; set; }
        public Nullable<int> oid { get; set; }
        public decimal containerNo { get; set; }
        public string containerId { get; set; }
        public string containerMdStd { get; set; }
        public string goodsNo { get; set; }
        public string lclFlag { get; set; }
        public string goodsContaWt { get; set; }
        public string containerWt { get; set; }
    }
}
