//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报关单回执信息
    {
        public int id { get; set; }
        public string ediNo { get; set; }
        public string preEntryId { get; set; }
        public string userName { get; set; }
        public string loginTradecode { get; set; }
        public string seqNo { get; set; }
        public string noticeDate { get; set; }
        public string channel { get; set; }
        public string note { get; set; }
        public string declPort { get; set; }
        public string iEDate { get; set; }
        public string dDate { get; set; }
        public string fileName { get; set; }
        public string cusCiqNo { get; set; }
    }
}
