//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报关单随附单证
    {
        public int id { get; set; }
        public int oid { get; set; }
        public decimal certificateNo { get; set; }
        public string docuCode { get; set; }
        public string certCode { get; set; }
    }
}
