//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报关单表体
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string guid { get; set; }
        public string codeT { get; set; }
        public string codeS { get; set; }
        public string contrItem { get; set; }
        public string declPrice { get; set; }
        public string declTotal { get; set; }
        public string dutyMode { get; set; }
        public string goodsId { get; set; }
        public string prdtNo { get; set; }
        public string firstUnitStd { get; set; }
        public string qtyConv { get; set; }
        public string gUnitStd { get; set; }
        public string gModel { get; set; }
        public string gName { get; set; }
        public Nullable<decimal> gNo { get; set; }
        public string gQty { get; set; }
        public string originCountryStd { get; set; }
        public string secondUnitStd { get; set; }
        public string qty2 { get; set; }
        public string tradeCurrStd { get; set; }
        public string useTo { get; set; }
        public string workUsd { get; set; }
        public string destinationCountryStd { get; set; }
        public string ciqCode { get; set; }
        public string declGoodsEname { get; set; }
        public string origPlaceCode { get; set; }
        public string purpose { get; set; }
        public string prodValidDt { get; set; }
        public string prodQgp { get; set; }
        public string goodsAttr { get; set; }
        public string stuff { get; set; }
        public string unCode { get; set; }
        public string dangName { get; set; }
        public string dangPackType { get; set; }
        public string dangPackSpec { get; set; }
        public string engManEntCnm { get; set; }
        public string noDangFlag { get; set; }
        public string destCode { get; set; }
        public string goodsSpec { get; set; }
        public string goodsModel { get; set; }
        public string goodsBrand { get; set; }
        public string produceDate { get; set; }
        public string prodBatchNo { get; set; }
        public string districtCode { get; set; }
        public string ciqName { get; set; }
        public string mnufctrRegno { get; set; }
        public string mnufctrRegName { get; set; }
    }
}
