//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报关单随附单据
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string fileName { get; set; }
        public string edoccode { get; set; }
        public string edocfomattype { get; set; }
        public string opnote { get; set; }
        public string edoccopid { get; set; }
        public string edocownercode { get; set; }
        public string signunit { get; set; }
        public string signtime { get; set; }
        public string edocownername { get; set; }
        public string edocSize { get; set; }
        public string declType { get; set; }
        public string tradeFileName { get; set; }
    }
}
