//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报关单表头
    {
        public int id { get; set; }
        public string operType { get; set; }
        public string status { get; set; }
        public string needPdfSign { get; set; }
        public string ediNo { get; set; }
        public string userName { get; set; }
        public string agentCode { get; set; }
        public string agentName { get; set; }
        public string ownerCode { get; set; }
        public string ownerName { get; set; }
        public string tradeCo { get; set; }
        public string tradeName { get; set; }
        public string tradeCoScc { get; set; }
        public string agentCodeScc { get; set; }
        public string ownerCodeScc { get; set; }
        public string apprNo { get; set; }
        public string billNo { get; set; }
        public string contrNo { get; set; }
        public string declPort { get; set; }
        public string cutMode { get; set; }
        public string distinatePortStd { get; set; }
        public string ediId { get; set; }
        public string ieFlag { get; set; }
        public string feeCurrStd { get; set; }
        public string feeMark { get; set; }
        public string feeRate { get; set; }
        public string grossWt { get; set; }
        public string iEDate { get; set; }
        public string iEPort { get; set; }
        public string insurCurrStd { get; set; }
        public string insurMark { get; set; }
        public string insurRate { get; set; }
        public string licenseNo { get; set; }
        public string manualNo { get; set; }
        public string netWt { get; set; }
        public string noteS { get; set; }
        public string otherCurrStd { get; set; }
        public string otherMark { get; set; }
        public string otherRate { get; set; }
        public string packNo { get; set; }
        public string printDate { get; set; }
        public string preEntryId { get; set; }
        public string seqNo { get; set; }
        public string tradeCountryStd { get; set; }
        public string tradeModeStd { get; set; }
        public string trafModeStd { get; set; }
        public string trafName { get; set; }
        public string transMode { get; set; }
        public string wrapTypeStd { get; set; }
        public string chkSurety { get; set; }
        public string billType { get; set; }
        public string promiseItmes { get; set; }
        public string tradeAreaCodeStd { get; set; }
        public string checkFlow { get; set; }
        public string taxAaminMark { get; set; }
        public string markNo { get; set; }
        public string despPortCode { get; set; }
        public string entyPortCode { get; set; }
        public string goodsPlace { get; set; }
        public string bLNo { get; set; }
        public string inspOrgCode { get; set; }
        public string specDeclFlag { get; set; }
        public string purpOrgCode { get; set; }
        public string despDate { get; set; }
        public string cmplDschrgDt { get; set; }
        public string correlationReasonFlag { get; set; }
        public string vsaOrgCode { get; set; }
        public string origBoxFlag { get; set; }
        public string declareName { get; set; }
        public string noOtherPack { get; set; }
        public string orgCode { get; set; }
        public string overseasConsignorCode { get; set; }
        public string overseasConsignorCname { get; set; }
        public string overseasConsignorEname { get; set; }
        public string overseasConsignorAddr { get; set; }
        public string overseasConsigneeCode { get; set; }
        public string overseasConsigneeEname { get; set; }
        public string domesticConsigneeEname { get; set; }
        public string correlationNo { get; set; }
        public string collecttax { get; set; }
        public string twoAudit { get; set; }
        public string taxNo { get; set; }
        public string ramanualno { get; set; }
        public string radeclno { get; set; }
        public string storeno { get; set; }
        public string voyageNo { get; set; }
        public string prdtid { get; set; }
        public string tradeCiqCode { get; set; }
        public string ownerCiqCode { get; set; }
        public string declCiqCode { get; set; }
    }
}
