//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报税单表头
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string ediNo { get; set; }
        public string fileName { get; set; }
        public string seqNo { get; set; }
        public string iEFlag { get; set; }
        public string declPort { get; set; }
        public string dDate { get; set; }
        public string tradeCo { get; set; }
        public string tradeName { get; set; }
        public string inRatio { get; set; }
        public string tradeMode { get; set; }
        public string cutMode { get; set; }
        public string transMode { get; set; }
        public string feeMark { get; set; }
        public string feeCurr { get; set; }
        public string feeRate { get; set; }
        public string insurMark { get; set; }
        public string insurCurr { get; set; }
        public string insurRate { get; set; }
        public string otherMark { get; set; }
        public string otherCurr { get; set; }
        public string otherRate { get; set; }
        public string manualNo { get; set; }
        public string tradeCoScc { get; set; }
        public string grossWt { get; set; }
        public string noteS { get; set; }
        public string legalLiability { get; set; }
        public string sign { get; set; }
        public string messId { get; set; }
        public string certSeqNo { get; set; }
        public string status { get; set; }
        public string fDate { get; set; }
        public string taxNo { get; set; }
    }
}
