//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 报税单表体
    {
        public int id { get; set; }
        public int oid { get; set; }
        public decimal gNo { get; set; }
        public string ediNo { get; set; }
        public string seqNo { get; set; }
        public string formListGuid { get; set; }
        public string codeTs { get; set; }
        public string gName { get; set; }
        public string originCountry { get; set; }
        public string agreementId { get; set; }
        public string qty1 { get; set; }
        public string unit1 { get; set; }
        public string qty2 { get; set; }
        public string unit2 { get; set; }
        public string tradeCurr { get; set; }
        public string declPrice { get; set; }
        public string declTotal { get; set; }
        public string dutyMode { get; set; }
        public string antidumping { get; set; }
        public string antisubsidy { get; set; }
        public string dutyValue { get; set; }
        public string dutyRate { get; set; }
        public string qtyDutyRate { get; set; }
        public string regRate { get; set; }
        public string qtyRegRate { get; set; }
        public string taxRate { get; set; }
        public string antidumpingRate { get; set; }
        public string antisubsidyRate { get; set; }
        public string trashfundRate { get; set; }
    }
}
