//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 特许权使用费申请
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string pricePreDeterminNo { get; set; }
        public string taxRoyaltyDeclType { get; set; }
        public string contractNo { get; set; }
        public string authorizer { get; set; }
        public string authorizedPerson { get; set; }
        public string payType { get; set; }
        public string payTime { get; set; }
        public string payPeriod { get; set; }
        public string effectiveDateTime { get; set; }
        public string expirationDateTime { get; set; }
        public string royaltyAmount { get; set; }
        public string curr { get; set; }
        public string royaltyFeeType { get; set; }
        public string edocType { get; set; }
        public string statment { get; set; }
        public string isSecret { get; set; }
        public string isCusAudit { get; set; }
        public string isCusPricePreDetermin { get; set; }
        public string issueDateTime { get; set; }
        public string periodStartDate { get; set; }
        public string periodEndDate { get; set; }
    }
}
