//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 许可证信息
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string guid { get; set; }
        public Nullable<decimal> goodsNo { get; set; }
        public string licTypeCode { get; set; }
        public string licenceNo { get; set; }
        public string licWrtofDetailNo { get; set; }
        public string licWrtofQty { get; set; }
        public string licWrtofQtyUnit { get; set; }
    }
}
