//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace change
{
    using System;
    using System.Collections.Generic;
    
    public partial class 许可证VIN信息
    {
        public int id { get; set; }
        public int oid { get; set; }
        public string licenceNo { get; set; }
        public string lictypeCode { get; set; }
        public string vinNo { get; set; }
        public Nullable<System.DateTime> billLadDate { get; set; }
        public string qualityQgp { get; set; }
        public string motorNo { get; set; }
        public string vinCode { get; set; }
        public string chassisNo { get; set; }
        public Nullable<decimal> invoiceNum { get; set; }
        public string prodCnnm { get; set; }
        public string prodEnnm { get; set; }
        public string modelEn { get; set; }
        public string pricePerUnit { get; set; }
        public string invoiceNo { get; set; }
    }
}
